require('dotenv').config({path:'.env.local'});
const { Pool } = require('pg');
const xlsx = require('xlsx');

const pool = new Pool({ connectionString: process.env.DATABASE_URL });

async function seedBOM() {
  try {
    // 1. Create table
    await pool.query(`
      CREATE TABLE IF NOT EXISTS production_bom (
        id SERIAL PRIMARY KEY,
        source_sheet VARCHAR(50),
        specification VARCHAR(255),
        group_name VARCHAR(255),
        part_name VARCHAR(255),
        part_no VARCHAR(100),
        unit VARCHAR(50),
        qty NUMERIC,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `);
    
    // Clear existing data to avoid duplicates on re-run
    await pool.query(`TRUNCATE TABLE production_bom RESTART IDENTITY;`);

    // 2. Parse Excel
    const workbook = xlsx.readFile('d:\\Office\\printCampany\\File\\ALL PARTS BOM.xlsx');
    const bomData = [];
    let autogenCounter = 1;

    // Sheet 1
    const sheet1 = workbook.Sheets['Sheet1'];
    const data1 = xlsx.utils.sheet_to_json(sheet1, { header: 1 });
    let headerRowIdx = 0;
    for(let i=0; i<data1.length; i++) {
      if (data1[i] && data1[i].includes('PART NO')) {
        headerRowIdx = i; break;
      }
    }
    for(let i=headerRowIdx+1; i<data1.length; i++) {
      const row = data1[i];
      if (!row || (!row[2] && !row[3] && !row[4])) continue; // empty row
      
      let partNo = row[4];
      if (!partNo || String(partNo).trim() === '') {
        partNo = `GEN-PART-${String(autogenCounter).padStart(4, '0')}`;
        autogenCounter++;
      }

      bomData.push({
        source_sheet: 'Sheet1',
        specification: row[1] || '',
        group_name: row[2] || '',
        part_name: row[3] || '',
        part_no: String(partNo).trim(),
        unit: row[5] || '',
        qty: parseFloat(row[6]) || 0
      });
    }

    // TYPE-2
    const sheet2 = workbook.Sheets['TYPE-2'];
    const data2 = xlsx.utils.sheet_to_json(sheet2, { header: 1 });
    let headerRowIdx2 = 0;
    for(let i=0; i<data2.length; i++) {
      if (data2[i] && data2[i].includes('Component Desc')) {
        headerRowIdx2 = i; break;
      }
    }
    for(let i=headerRowIdx2+1; i<data2.length; i++) {
      const row = data2[i];
      if (!row || (!row[1] && !row[2])) continue; 

      let partNo = row[1];
      if (!partNo || String(partNo).trim() === '') {
        partNo = `GEN-PART-${String(autogenCounter).padStart(4, '0')}`;
        autogenCounter++;
      }

      bomData.push({
        source_sheet: 'TYPE-2',
        specification: '',
        group_name: 'TYPE-2 Component',
        part_no: String(partNo).trim(),
        part_name: row[2] || '',
        unit: row[3] || '',
        qty: parseFloat(row[4]) || 0
      });
    }

    // 3. Insert into DB
    let inserted = 0;
    for (const item of bomData) {
      await pool.query(
        `INSERT INTO production_bom 
        (source_sheet, specification, group_name, part_name, part_no, unit, qty) 
        VALUES ($1, $2, $3, $4, $5, $6, $7)`,
        [item.source_sheet, item.specification, item.group_name, item.part_name, item.part_no, item.unit, item.qty]
      );
      inserted++;
    }

    console.log(`Successfully inserted ${inserted} BOM items. Autogenerated ${autogenCounter - 1} part numbers.`);
  } catch(e) {
    console.error("Error seeding BOM:", e);
  } finally {
    pool.end();
  }
}

seedBOM();
